### ISSUE TITLE
help interpreting why logBaseCalling might be failing

### ISSUE THREAD

**Issue by xguse** [biocorecrg/master_of_pores#109]
I am sorry to bother you all but I can't quite figure out what is going on here. 

As far as I can tell `WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.` should not be fatal should it? Where am I going wrong here?

```
➜ nextflow -c /home/ubuntu/master_of_pores/nextflow.global.config run  -params-file /home/ubuntu/master_of_pores/NanoPreprocess/run_configs/params.lib03_test.yaml nanopreprocess.nf -with-docker -profile local
N E X T F L O W  ~  version 19.10.0
Launching `nanopreprocess.nf` [marvelous_khorana] - revision: 070dd5f042
WARN: Access to undefined parameter `demultiplexing` -- Initialise it to a default value eg. `params.demultiplexing = some_value`
WARN: Access to undefined parameter `demultiplexing_opt` -- Initialise it to a default value eg. `params.demultiplexing_opt = some_value`
WARN: Access to undefined parameter `demulti_fast5` -- Initialise it to a default value eg. `params.demulti_fast5 = some_value`
WARN: Access to undefined parameter `email` -- Initialise it to a default value eg. `params.email = some_value`
╔╦╗┌─┐┌─┐┌┬┐┌─┐┬─┐  ┌─┐┌─┐  ╔═╗╔═╗╦═╗╔═╗╔═╗
║║║├─┤└─┐ │ ├┤ ├┬┘  │ │├┤   ╠═╝║ ║╠╦╝║╣ ╚═╗
╩ ╩┴ ┴└─┘ ┴ └─┘┴└─  └─┘└    ╩  ╚═╝╩╚═╚═╝╚═╝

====================================================
BIOCORE@CRG Preprocessing of Nanopore direct RNA - N F  ~  version 0.1
====================================================

kit                       : SQK-LSK110
flowcell                  : FAQ55277
fast5                     : /home/ubuntu/ebs/data/seqs/input/lib03/fast5_*/*.fast5
reference                 : /home/ubuntu/ebs/data/seqs/references/gisaid.spike.ref.fasta
annotation                : null

ref_type                  : transcriptome
seq_type                  : DNA

output                    : /home/ubuntu/ebs/data/seqs/output/lib03_test
qualityqc                 : 5
granularity               : null

basecaller                : guppy
basecaller_opt            : null
GPU                       : ON
demultiplexing            : null
demultiplexing_opt        : null
demulti_fast5                 : null

filter                    : null
filter_opt                : null
mapper                    : minimap2
mapper_opt                : null
map_type                  : unspliced

counter                   : YES
counter_opt               : null

downsampling                      : null

variant_caller            : NO
variant_opt               : null

email                     : null
executor >  local (3)
[ba/06efa5] process > testInput (FAQ55277_pass_d75244b2_860.fast5) [100%] 1 of 1 ✔
[82/7ab4ca] process > logBaseCalling                               [100%] 1 of 1, failed: 1 ✘
[87/93d147] process > baseCalling (guppy-fast5_*-0)                [  0%] 0 of 1
[-        ] process > concatenateFastQFiles                        -
executor >  local (3)
[ba/06efa5] process > testInput (FAQ55277_pass_d75244b2_860.fast5) [100%] 1 of 1 ✔
[82/7ab4ca] process > logBaseCalling                               [100%] 1 of 1, failed: 1 ✘
[87/93d147] process > baseCalling (guppy-fast5_*-0)                [100%] 1 of 1, failed: 1
[-        ] process > concatenateFastQFiles                        -
[-        ] process > QC                                           -
[-        ] process > fastQC                                       -
[-        ] process > mapping                                      -
[-        ] process > counting                                     -
[-        ] process > joinCountQCs                                 -
[-        ] process > alnQC                                        -
[-        ] process > joinAlnQCs                                   -
[-        ] process > alnQC2                                       -
[-        ] process > multiQC                                      -
Sending the email to null
MultiFast5 files detected!
WARN: Killing pending tasks (1)
Error executing process > 'logBaseCalling'

Caused by:
  Process `logBaseCalling` terminated with an error exit status (1)

Command executed:

  echo '*********************************'
  guppy_basecaller --version
  guppy_basecaller --print_workflows | grep FAQ55277 | grep SQK-LSK110
  echo '*********************************'

Command exit status:
  1

Command output:
  *********************************
  : Guppy Basecalling Software, (C) Oxford Nanopore Technologies, Limited. Version 3.4.5+fb1fbfb

Command error:
  WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.

Work dir:
  /home/ubuntu/master_of_pores/NanoPreprocess/work/82/7ab4ca8127f24419c3fa193d19b1fd

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
Failed to invoke `workflow.onComplete` event handler

 -- Check script 'nanopreprocess.nf' at line: 811 or see '.nextflow.log' file for more details
```

**Comment by lucacozzuto** [comment]
Can you post your params.config file? You have a lot of null. And which version of guppy are you using?

**Comment by xguse** [comment]
```yaml

kit: SQK-LSK110
flowcell: FAQ55277
fast5: /home/ubuntu/ebs/data/seqs/input/lib03/fast5_*/*.fast5
reference: /home/ubuntu/ebs/data/seqs/references/gisaid.spike.ref.fasta
annotation: 
ref_type: transcriptome

seq_type: DNA
output: /home/ubuntu/ebs/data/seqs/output/lib03_test
qualityqc: 5
granularity:  

basecaller: guppy
basecaller_opt: 
GPU: "ON"

# demultiplexing:    
# demultiplexing_opt: -m pAmps-final-actrun_newdata_nanopore_UResNet20v2_model.030.h5
# demulti_fast5: OFF    

filter: 
filter_opt: 

mapper: minimap2
mapper_opt: 
map_type: unspliced

counter: "YES"
counter_opt: 

variant_caller: "NO"
variant_opt: 

downsampling: 

```

and I ran this to install guppy

```bash
wget https://mirror.oxfordnanoportal.com/software/analysis/ont-guppy_3.4.5_linux64.tar.gz 
tar -zvxf ont-guppy_3.4.5_linux64.tar.gz
mkdir NanoPreprocess/bin/ont-guppy_3.4.5_linux64
mv ont-guppy NanoPreprocess/bin/ont-guppy_3.4.5_linux64
cd NanoPreprocess/bin
ln -s ont-guppy_3.4.5_linux64/ont-guppy/bin/guppy_* .
cd ../../
rm -fr ont-guppy_3.4.5_linux64.tar.gz
```
